<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 *
 * See COPYING.txt for license details.
 */
?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()) : ?>
    <br />
    <table class="shipment-track">
        <thead>
            <tr>
                <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
                <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_shipment->getAllTracks() as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td>
                        <?php $url = $block->getTrackingUrl($_item) ?>
                        <?php if ($url) : ?>
                            <a href="<?= $block->escapeHtml($url) ?>" target="_blank" rel="nofollow noopener">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php else : ?>
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
